# Generated by Django 4.2.2 on 2023-07-26 13:02

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('usuario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='usuario',
            name='foto_perfil',
            field=models.ImageField(default='../static/default-user.png', upload_to='usuarios'),
        ),
    ]
