# Generated by Django 4.2.2 on 2023-07-22 12:00

from django.db import migrations, models
import django.db.models.deletion
import django.utils.timezone


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(max_length=30)),
            ],
        ),
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('titulo', models.CharField(max_length=30)),
                ('resumen', models.TextField()),
                ('contenido', models.TextField()),
                ('imagen', models.ImageField(blank=True, default='articulo/default_articulo.jpg', null=True, upload_to='articulo')),
                ('is_active', models.BooleanField(default=True)),
                ('publicado', models.DateTimeField(default=django.utils.timezone.now, editable=False)),
                ('categoria', models.ForeignKey(default='Sin categoría', null=True, on_delete=django.db.models.deletion.SET_NULL, to='articulo.categoria')),
            ],
            options={
                'ordering': ('-publicado',),
            },
        ),
    ]
