# Generated by Django 4.2.2 on 2023-06-26 20:31

from django.db import migrations, models


class Migration(migrations.Migration):

    initial = True

    dependencies = [
    ]

    operations = [
        migrations.CreateModel(
            name='Articulo',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('fecha', models.DateField(auto_now=True, verbose_name='Fecha de publicacion')),
                ('titulo', models.CharField(help_text='Ingrese el titulo del articulo', max_length=100, verbose_name='Titulo')),
                ('resumen', models.TextField(help_text='Ingrese aqui su resumen', verbose_name='Resumen')),
                ('contenido', models.TextField(help_text='Ingrese aqui el contenido del articulo', verbose_name='Contenido')),
            ],
        ),
    ]
