# Generated by Django 4.2.2 on 2023-07-22 12:06

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0002_initial'),
    ]

    operations = [
        migrations.AddField(
            model_name='categoria',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
    ]
