# Generated by Django 4.2.2 on 2023-06-27 20:06

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0002_alter_genero_pertenece_a_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='pertenece_a_genero',
            field=models.ForeignKey(blank=True, default='', on_delete=django.db.models.deletion.CASCADE, to='articulo.genero'),
        ),
    ]
