# Generated by Django 4.2.2 on 2023-07-14 12:54

from django.conf import settings
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        migrations.swappable_dependency(settings.AUTH_USER_MODEL),
        ('articulo', '0002_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='articulo',
            name='activo',
        ),
        migrations.AddField(
            model_name='articulo',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='articulo',
            name='creado_por',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to=settings.AUTH_USER_MODEL, verbose_name='creador'),
        ),
    ]
