# Generated by Django 4.2.2 on 2023-07-15 14:58

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0003_remove_articulo_activo_articulo_is_active_and_more'),
    ]

    operations = [
        migrations.RenameField(
            model_name='categoria',
            old_name='activo',
            new_name='is_active',
        ),
    ]
