# Generated by Django 4.2.2 on 2023-07-20 14:43

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0004_rename_activo_categoria_is_active'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='imagen',
            field=models.ImageField(blank=True, default='static/default-articulo.jpg', null=True, upload_to='articulo/'),
        ),
    ]
