# Generated by Django 4.2.2 on 2023-06-27 20:09

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0004_alter_genero_pertenece_a_genero'),
    ]

    operations = [
        migrations.AlterField(
            model_name='genero',
            name='pertenece_a_genero',
            field=models.ForeignKey(null=True, on_delete=django.db.models.deletion.DO_NOTHING, to='articulo.genero'),
        ),
    ]
