# Generated by Django 4.2.2 on 2023-06-28 10:11

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0005_alter_genero_pertenece_a_genero'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='genero',
            name='pertenece_a_genero',
        ),
        migrations.AddField(
            model_name='genero',
            name='padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='Genero_padre', to='articulo.genero'),
        ),
    ]
