# Generated by Django 4.2.2 on 2023-06-29 19:27

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0006_remove_genero_pertenece_a_genero_genero_padre'),
    ]

    operations = [
        migrations.CreateModel(
            name='Categoria',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('nombre', models.CharField(help_text='Nombre de la categoria', max_length=35, verbose_name='categoria')),
                ('padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='categoria_padre', to='articulo.categoria')),
            ],
        ),
        migrations.RemoveField(
            model_name='articulo',
            name='genero',
        ),
        migrations.DeleteModel(
            name='Genero',
        ),
        migrations.AddField(
            model_name='articulo',
            name='categoria',
            field=models.ForeignKey(help_text='Ingrese la categoria', null=True, on_delete=django.db.models.deletion.CASCADE, to='articulo.categoria', verbose_name='Categoria'),
        ),
    ]
