# Generated by Django 4.2.2 on 2023-06-29 19:57

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0008_articulo_imagen'),
    ]

    operations = [
        migrations.AlterField(
            model_name='articulo',
            name='fecha',
            field=models.DateField(editable=False, verbose_name='Fecha de publicacion'),
        ),
    ]
