# Generated by Django 4.2.2 on 2023-07-12 13:04

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    initial = True

    dependencies = [
        ('articulo', '0001_initial'),
    ]

    operations = [
        migrations.CreateModel(
            name='Comentario',
            fields=[
                ('id', models.BigAutoField(auto_created=True, primary_key=True, serialize=False, verbose_name='ID')),
                ('contenido', models.CharField(default='', help_text='Ingrese aqui su comentario', max_length=100, verbose_name='Texto')),
                ('creado', models.DateField(default=datetime.datetime(2023, 7, 12, 10, 4, 1, 85024), editable=False, verbose_name='Fecha de publicacion')),
                ('articulo', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='articulo.articulo', verbose_name='Articulo')),
                ('comentario_padre', models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comentario.comentario', verbose_name='Comentario')),
            ],
        ),
    ]
