# Generated by Django 4.2.2 on 2023-07-13 11:22

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='creado',
            field=models.DateField(default=datetime.datetime(2023, 7, 13, 8, 22, 10, 792281), editable=False, verbose_name='Fecha de publicacion'),
        ),
    ]
