# Generated by Django 4.2.2 on 2023-07-11 11:53

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='id_comentario',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='modificado',
        ),
    ]
