# Generated by Django 4.2.2 on 2023-06-28 19:03

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0002_comentario_imagen'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='imagen',
        ),
        migrations.RemoveField(
            model_name='comentario',
            name='usuario',
        ),
    ]
