# Generated by Django 4.0.6 on 2023-08-03 12:00

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0002_initial'),
    ]

    operations = [
        migrations.RenameField(
            model_name='comentario',
            old_name='usuario',
            new_name='creado_por',
        ),
    ]
