# Generated by Django 4.2.2 on 2023-07-11 11:55

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0002_remove_comentario_id_comentario_and_more'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='comentario',
            name='imagen',
        ),
    ]
