# Generated by Django 4.2.2 on 2023-07-14 01:38

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0002_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='creado',
            field=models.DateField(default=datetime.datetime(2023, 7, 13, 22, 38, 10, 343380), editable=False, verbose_name='Fecha de publicacion'),
        ),
    ]
