# Generated by Django 4.2.2 on 2023-06-28 19:31

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0003_remove_comentario_imagen_remove_comentario_usuario'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='id_comentario',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, related_name='comentario_comentado', to='comentario.comentario'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.CharField(blank=True, help_text='Ingrese aqui su comentario', max_length=100, null=True, verbose_name='Comentario'),
        ),
    ]
