# Generated by Django 4.2.2 on 2023-07-12 00:27

import datetime
from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0003_remove_comentario_imagen'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='comentario_padre',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.CASCADE, to='comentario.comentario', verbose_name='Comentario'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='creado',
            field=models.DateField(default=datetime.datetime(2023, 7, 11, 21, 27, 48, 442050), editable=False, verbose_name='Fecha de publicacion'),
        ),
    ]
