# Generated by Django 4.2.2 on 2023-07-12 10:30

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0004_comentario_comentario_padre_alter_comentario_creado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='creado',
            field=models.DateField(default=datetime.datetime(2023, 7, 12, 7, 30, 43, 297511), editable=False, verbose_name='Fecha de publicacion'),
        ),
    ]
