# Generated by Django 4.2.2 on 2023-06-28 19:34

from django.db import migrations, models
import django.db.models.deletion


class Migration(migrations.Migration):

    dependencies = [
        ('articulo', '0006_remove_genero_pertenece_a_genero_genero_padre'),
        ('comentario', '0004_comentario_id_comentario_alter_comentario_comentario'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='articulo',
            field=models.ForeignKey(blank=True, null=True, on_delete=django.db.models.deletion.SET_NULL, to='articulo.articulo', verbose_name='Articulo'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='comentario',
            field=models.CharField(help_text='Ingrese aqui su comentario', max_length=100, verbose_name='Comentario'),
        ),
    ]
