# Generated by Django 4.2.2 on 2023-07-14 12:54

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0005_alter_comentario_creado'),
    ]

    operations = [
        migrations.AddField(
            model_name='comentario',
            name='is_active',
            field=models.BooleanField(default=True),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='creado',
            field=models.DateField(default=datetime.datetime(2023, 7, 14, 9, 54, 10, 285755), editable=False, verbose_name='Fecha de publicacion'),
        ),
    ]
