# Generated by Django 4.2.2 on 2023-07-15 13:10

import datetime
from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0006_comentario_is_active_alter_comentario_creado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='creado',
            field=models.DateTimeField(default=datetime.datetime(2023, 7, 15, 10, 10, 56, 520973), editable=False, verbose_name='Fecha de publicacion'),
        ),
    ]
