# Generated by Django 4.2.2 on 2023-07-15 13:37

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('comentario', '0007_alter_comentario_creado'),
    ]

    operations = [
        migrations.AlterField(
            model_name='comentario',
            name='contenido',
            field=models.CharField(default='', help_text='Ingrese aqui su comentario', max_length=200, verbose_name='Texto'),
        ),
        migrations.AlterField(
            model_name='comentario',
            name='creado',
            field=models.DateTimeField(editable=False, verbose_name='Fecha de publicacion'),
        ),
    ]
